### ISSUE TITLE
建议 | 优化分包机制

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo-aot#11]
### 建议将分包对应的`js`、`css`、`components`等资源文件打包进对应的分包文件夹，以减小主包的大小。
![281542713422_ pic](https://user-images.githubusercontent.com/23731087/48771057-35e5d000-ecfb-11e8-894e-fd224ca3dac9.jpg)

### 如下所示，构建工具将 packageA 的资源文件打包进了根路径下的 `static` 和 `components` 里，主包大小是 `456.5 KB`
![261542713236_ pic_hd](https://user-images.githubusercontent.com/23731087/48770886-c243c300-ecfa-11e8-9ba9-cb09fc1ff7ef.jpg)

### 然后我手动将 packageA 的资源文件移动到 packageA 文件夹里后，主包大小变为 `441.5 KB`
![291542713659_ pic_hd](https://user-images.githubusercontent.com/23731087/48771093-4bf39080-ecfb-11e8-9b00-10c05d878c81.jpg)

### 最好是能够将图片等文件也一并打包进XX包对应的文件夹里。

**Comment by fengzilong** [comment]
### 组件

- [ ] components ->[package]/components
- [ ] component content
- [ ] components/slots -> [package]/components/slots

组件转移，转移后的引用路径处理，分包专属 slots 的提取

### 页面

- [ ] page content

引用路径变化，需区分 分包专属组件 / 公共组件，引用路径有所区别

### 静态资源

- [ ] static -> [package]/static

**Comment by fengzilong** [comment]
@auven @b2nil 把工程的 @megalo/target 升下 0.4.2 看看，有问题可以在这个 issue 继续讨论

**Comment by auven** [comment]
**这里我建议是`@megalo/target`不去处理`js`、`css`的路径，只需处理`components`的打包路径，因为在`webpack`的配置里可以实现它们的打包路径。**

## @megalo/target 0.3.0

> "@megalo/target": "^0.3.0", "@megalo/template-compiler": "^0.4.0"

如下，在`@megalo/target 0.3.0`版本下，`/build/createBaseConfig.js`
``` js
...
function createBaseConfig( platform = 'wechat' ) {
  const cssExt = CSS_EXT[platform]

  return {
    ...
    output: {
      path: _.resolve( `dist-${platform}/` ),
      filename: '[name]/main.js',   <-- 修改 js 打包路径
      // chunkFilename: 'static/js/[id].js'
    },
    ...
    plugins: [
      ...
      new MiniCssExtractPlugin( {
        filename: `[name]/main.${cssExt}`,  <-- 修改 css 打包路径
      } )
      ...
    ]
  }
}
```
打包后路径如下，`js`、`wxss`路径很清晰
![11543509563_ pic_hd](https://user-images.githubusercontent.com/23731087/49237057-67b41080-f438-11e8-8874-482789d4d8da.jpg)

## @megalo/target 0.4.2

> "@megalo/target": "^0.4.2", "@megalo/template-compiler": "^0.4.0"

而使用`@megalo/target 0.4.2`，打包后路径如下，相关资源路径有点冗杂
![21543509801_ pic_hd](https://user-images.githubusercontent.com/23731087/49237521-54557500-f439-11e8-92dc-094520cf83d9.jpg)

**Comment by fengzilong** [comment]
这样子的话，有点强依赖webpack的配置了，最好是能在用户不知情的情况下完成js/css的分包，路径有点冗杂的问题其实可以忽略，因为大多数情况下你不需要关心生成的pages底下的文件内容

**Comment by fengzilong** [comment]
js/css的体积占了很大比例，所以这部分是必须内部处理掉的，你说的做法属于奇技淫巧，比起这个还是倾向于统一处理，路径长的问题可以后面再优化下，比如把packageA这层去掉

**Comment by auven** [comment]
这个是因为前几天主包超2M了，实在没办法才想出来的。。。哈哈哈。

**现在使用`@megalo/target 0.4.2`发现一个问题，就是我用`copy-webpack-plugin`拷贝过来的图片，发现路径错误了。** 如下是我拷贝图片的代码`copyImages.js`
``` js
const CopyWebpackPlugin = require('copy-webpack-plugin')
const fs = require('fs')
const fse = require('fs-extra')
const _ = require('./util')
const { walk4Obj } = require('./util')
const exp4parse = /\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\/|\/\/[^\r\n]*|\s/g

// 获取主包images路径和分包images路径
function copyImages(appMainFile) {
  let txt = '',
    mainObj = {},
    subpackages = [],
    imagesPath = []
  const mainImagesPath = _.resolve('src/images')
  fse.ensureDirSync(mainImagesPath)
  imagesPath.push({
    from: mainImagesPath,
    to: _.resolve('dist-wechat/images')
  })

  try {
    txt = fs.readFileSync(appMainFile, 'utf8')
    txt = txt.replace(exp4parse, '')
    mainObj = walk4Obj(txt, 'exportdefault')['config'] || {}

    subpackages = mainObj.subPackages || []

    subpackages.forEach(sp => {
      const { root } = sp
      const packagePath = _.resolve(`src/${root}`)
      if (fs.statSync(packagePath).isDirectory()) {
        const subpackImagesPath = _.resolve(packagePath, 'images')
        fse.ensureDirSync(subpackImagesPath)
        imagesPath.push({
          from: subpackImagesPath,
          to: _.resolve(`dist-wechat/${root}/images`)
        })
      }
    })
  } catch (e) {
    console.log(e)
  }

  console.log(imagesPath)

  return new CopyWebpackPlugin([...imagesPath])
}

module.exports = copyImages
```
我这里是给分包`packageA`创建了`images`文件夹，并且用`copy-webpack-plugin`拷贝到`dist-wechat/packageA/images`，结果发现拷贝后的路径错了，变成了`dist-wechat/packageA/packageA/images`。拷贝后的路径如下：
![31543545797_ pic_hd](https://user-images.githubusercontent.com/23731087/49265368-c30fee00-f48c-11e8-887d-2bdead50d7fa.jpg)

**Comment by b2nil** [comment]
@fengzilong 

@megalo/target@0.4.2 我跑起来还是不正常，分包页面引用路劲都不对。编译后的 wxml 文件全部在主包的 `components` 目录下。分包没有出现 `components` 目录。

另外 wxss 文件引用路径中间出现了一个点：
```
@import "../../../../pages/packageB/./static/css/pages/packageB/pages/test/index.wxss"
```
问题复现： [repo](https://github.com/b2nil/issue-demo.git)

**Comment by fengzilong** [comment]
好的，正在看

**Comment by auven** [comment]
@fengzilong  我这边使用`@megalo/target@0.4.3`正常了，感谢大佬们！！

**Comment by fengzilong** [comment]
@auven 不客气，遇到其他问题也欢迎反馈~

**Comment by b2nil** [comment]
@fengzilong 
问题是 `packageA` 的页面也找不到模板。
你那边跑这个 demo 时， `packageA` 的页面能正常显示？

`.` 的问题的确是不影响使用。

**Comment by fengzilong** [comment]
我这里的打包结果和你不一样，是符合预期的，页面在开发者工具中打开也可以正常访问

**Comment by fengzilong** [comment]
这个 issue 我先关闭了，有问题可以继续在这里讨论，或者新开 issue 反馈

**Comment by b2nil** [comment]
@fengzilong 

由于我用的是 Windows， 路径处理时有点蛋疼。下次沟通时我把使用的系统标明。

调试了一下源码后发现，`@megalo\target\lib\plugins\MegaloPlugin.js` 中 `attachLoaderContext` 的回调函数传入的 `resourcePath` 路径用的是 `\`，从而导致`@megalo\target\lib\utils\subpackages.js` 中的正则不能正确判断是否是分包。

在 `@megalo\target\lib\utils\removeExtension.js` 将  `resourcePath`  路径中的 `\` 统一替换成 `/ ` 后，便可以正常使用了。至于会不会影响其他系统，需要评估一下。
```javascript
// @megalo\target\lib\utils\removeExtension.js
module.exports = function removeExtension(str, extension) {        
	if (extension) {
		const reg = new RegExp(extension.replace(/\./, '\\.') + '$')
		str.replace(/\\/g, '/')  // 将路径中的 \ 统一替换成 /
		return str.replace(reg, '')
	}
        str.replace(/\\/g, '/')  // 将路径中的 \ 统一替换成 /
	return str.replace(/\.\w+$/g, '') 
}
```

现在还有一个问题，靠你们了^_-：
- 分包页面入口文件的模板在总包 `components` 下也拷贝了一份。虽然不影响使用，但会导致总包变大。

![tree](https://user-images.githubusercontent.com/16893585/49288464-c5e5ff80-f4db-11e8-985c-22bdd8dde58f.jpg)

**Comment by b2nil** [comment]
@fengzilong
FYI
做了两处修改后，分包无论放在 `src` 目下，还是放在 `src/pages` 目录，windows 下的表现都符合预期。

[修改的代码详见这里](https://github.com/b2nil/megalo-aot/commit/ce7d5bb36c5c95bf75477ebe9803d39d88dd7234)

**Comment by auven** [comment]
@b2nil @fengzilong 
window 下确实有 bug ，打包的`components`会找不到路径

**Comment by b2nil** [comment]
@auven
可以试试看我修改后临时替代的包是否有效:  
npm i @b2nil/megalo-target --save

**Comment by auven** [comment]
@fengzilong 
最新版`@megalo/target@0.4.9`在`windows`下还是存在问题

**Comment by fengzilong** [comment]
已经修复了，等我解决了另一个问题再一起发个版

**Comment by fengzilong** [comment]
@auven windows 路径的问题试下 @megalo/target@0.4.10，另一个问题短时间修复不了，依赖另一个包的改动，先发个版😅

**Comment by auven** [comment]
@fengzilong  我们试了一下可以了，感谢~
