### ISSUE TITLE
集中式页面配置

### ISSUE THREAD

**Issue by UnableRegister** [kaola-fed/megalo-aot#12]
能像[mpvue-entry](https://github.com/F-loat/mpvue-entry)集中式页面配置，自动生成各页面的入口文件？现在的页面配置方式会产生很多的模板文件(eg: pages/index/index.js)和模版代码：
```import App from './index'
import Vue from 'vue'

const app = new Vue( App )

app.$mount()
```
看着好痛苦啊

**Comment by fengzilong** [comment]
@b2nil custom block 的想法很赞

```vue
<template></template>

<script></script>

<style></style>

<config>
  // app / page config
</config>
```

可以考虑支持下将 `.vue` 文件作为 app / page 入口，这样就可以少写一部分js样板代码了

**Comment by b2nil** [comment]
@fengzilong 
如果 `megalo` 能够支持直接将 `.vue` 文件作为 app 和 page 的入口，那就简直太棒了。
采用 `vue-template-compiler` 解析 sfc 中各个模块好像并不复杂。需要考虑一下原入口文件的 js 代码如何处理比较好。现在 megalo 好像是不支持在 .vue 文件中使用 Vue.extend() 的写法。

**Comment by fengzilong** [comment]
Vue.extend 的语法暂不支持解析，这些我会放在另一个 issue 里面处理

**Comment by fengzilong** [comment]
@UnableRegister @b2nil 

config配置
https://github.com/kaola-fed/megalo-aot/blob/ca2274fc9c60d1099ecbdd2105beb8529b317d46/examples/vue-mp/src/pages/counter/index.vue#L60-L64

webpack配置：
https://github.com/kaola-fed/megalo-aot/blob/ca2274fc9c60d1099ecbdd2105beb8529b317d46/examples/vue-mp/webpack.config.js#L19

理论上，app和page应该都可以直接指定.vue文件作为入口了

升级对应的 @megalo/target 版本即可：@megalo/target@0.4.7

**Comment by fengzilong** [comment]
> 给集中式页面配置补充一些功能建议：
> 
> 1. 能够配置公共的`config`。因为在实际使用过程中，有很多页面要用到相同的第三方小程序组件，如果在每个页面的`config`里写`usingComponents`太繁琐了。
> 2. 能够在页面级组件`mpType: 'page'`里配置`config`，即：
> 
> * xx.vue
> 
> ```js
> export default {
>   mpType: 'page',
>   config: {
>     ...
>   }
> }
> ```
> 
> 优先级：页面 vue 组件的 config > 页面的 config > 公共的 config，并且三者会合并。

我新建了一个 issue，可以在新的 issue 中继续讨论

https://github.com/kaola-fed/megalo-aot/issues/24
