### ISSUE TITLE
无法从index.js里import组件

### ISSUE THREAD

**Issue by Amorites** [kaola-fed/megalo-aot#14]
## 复现代码

https://github.com/Amorites/megalo-bug-report/blob/38e9d716a7c4ee5b3c8ad6a341a25cfec866fa51/src/pages/hello/hello.vue#L11

## 问题现象

![image](https://user-images.githubusercontent.com/13085465/49204243-301c7880-f3e6-11e8-9632-abd20fc3514b.png)

顺便一提，mpvue也有这个问题，之前看过一个[同样的问题](https://juejin.im/post/5aa9e3f86fb9a028c6756e01)

**Comment by fengzilong** [comment]
这个问题基本上解决不了，可以考虑在构建提示上给出一些更友好的提示

比如

importee.vue

```vue
<script>
  import { Button, Card } 'path/to/js/file'
</script>
```

path/to/js/file.js

```js
import Vue from 'Vue'
import Card from './Card.vue'

const Button = Vue.extend( {} )

export { Card: hoc( Card ), Button }
```

一旦涉及 js，那分析的工作就很难了

- hoc( Card ) 可能返回了一个全新的组件，这个时候我们拿到源组件也没有什么用处，而源组件也不一定可以直接拿到
- Button 在这里是用 **非单文件组件** 形式声明的，这就导致我们很难单独拿到它的模板和其他部分

megalo-aot 的构建过程很大程度上依赖于 Vue 的单文件组件，所以这块也只能在提示上想办法
