### ISSUE TITLE
引用本地图片 webpack不能打包

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo-aot#15]
image引用本地图片 webpack 不能打包进dist 

这块自己配置webpack吗 ？

**Comment by fengzilong** [comment]
@megalo/target@0.5.0
megalo@0.6.0

已修复 url-loader 的问题，不用使用 hack 的方式，直接使用 相对路径 引用图片即可

参考

https://github.com/kaola-fed/megalo-demo/blob/61e946c07abc0d6149e8d35b6cf84ea4c0cc2d0f/src/pages/img/index.vue#L3-L5
