### ISSUE TITLE
希望考虑下各个开发工具配置文件的保存问题

### ISSUE THREAD

**Issue by luckyyyyy** [kaola-fed/megalo-aot#16]
例如微信的 project.config.json 文件，Get Started 中建议把目录设置成dist，但是这其实也造成一个问题，导致不能轻易的去清空dist目录。

不清空的话之前的业务代码可能还遗留在里面，导致小程序开发工具上传会让包变得非常大，也可能会导致新手把资源文件放入dist，亦或者是老业务代码的dist残留一些资源文件。

**Comment by fengzilong** [comment]
[clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) 配合 [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) 一起使用，`project.config.json` 之类的配置文件存放在源码目录，使用 clean-webpack-plugin 拷贝过去即可

构建相关的文档和最佳实践后面会补上，感谢反馈
