### ISSUE TITLE
page级别的vue如果不指定mpType就会报错

### ISSUE THREAD

**Issue by luanwulin** [kaola-fed/megalo-aot#19]
我看了下源码做了mpType判断的，不知道哪里有问题，现在如果不指定就会报错
![image](https://user-images.githubusercontent.com/16553854/48830719-37250480-edb0-11e8-93b8-d84e2959017e.png)
只有找了个workaround，将src/index.js添加如下代码
```javascript
const oInit = Vue.prototype._init;
Vue.prototype._init = function (options) {
  !options.mpType && (options.mpType = 'page');
  oInit.call(this, options);
  return this
};
```
这样倒是可以用了，不过可以修复下么？

**Comment by fengzilong** [comment]
@luanwulin @Airkro 升级下 @megalo/target -> 0.4.4，代码中可以不写 mpType
