### ISSUE TITLE
如何使用url-loader自动处理template中的图片文件呢

### ISSUE THREAD

**Issue by sanriqing** [kaola-fed/megalo-aot#28]
添加webpack对图片的检测，配置对应loader，并在loader中debugger，发现实际并未掉用对应loader。

**Comment by fengzilong** [comment]
@megalo/target@0.5.0
megalo@0.6.0

已修复url-loader的问题

**Comment by fengzilong** [comment]
@megalo/target@0.5.0
megalo@0.6.0

已修复url-loader的问题
