### ISSUE TITLE
升级 @megalo/target@0.5.0 后运行报错

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo-aot#40]
- @megalo/target@0.5.0
- megalo@0.6.0
- @megalo/template-compiler@0.6.0

![image](https://user-images.githubusercontent.com/23731087/49808240-0aed1a00-fd97-11e8-8f27-3cf6a04eb7b4.png)

**Comment by b2nil** [comment]
我在使用 `App.vue` 作为小程序`app`入口时，如果`.vue` 文件中不写 `<template>...</template>`，也会遇到类似的错误：
```bash
PS E:\vueprojects\validate> yarn run dev:wechat
yarn run v1.12.3
$ webpack --config ./build/webpack.config.wechat.js -w

webpack is watching the files…

TypeError: Cannot set property 'root' of undefined
    at Object.keys.map.k (E:\vueprojects\validate\node_modules\@megalo\target\lib\plugins\MegaloPlugin.js:141:32)
    at Array.map (<anonymous>)
    at normalizePages (E:\vueprojects\validate\node_modules\@megalo\target\lib\plugins\MegaloPlugin.js:124:24)
    at compiler.hooks.emit.tap.compilation (E:\vueprojects\validate\node_modules\@megalo\target\lib\plugins\MegaloPlugin.js:97:9)
    at _err0 (eval at create (E:\vueprojects\validate\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (E:\vueprojects\validate\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at E:\vueprojects\validate\node_modules\copy-webpack-plugin\dist\index.js:118:24
error Command failed with exit code 1.
```
这是 `@megalo/template-compiler` 解析入口文件后返回的 `template` 为 `null`，从而导致 `MegaloPlugin.js` 中得到的 `app` 的 `entryComponent` 为 `undefined` 或者 `null`。

不知道这个情况是否与你遇到的情况类似。

**Comment by auven** [comment]
@b2nil  不是你这种情况，感觉像是处理图片这一块错误了。

**Comment by fengzilong** [comment]
@auven 有代码或可以复现的repo么？我在 megalo-demo 里面无法复现这个问题，不知道是不是你哪里用了比较特殊的写法

**Comment by fengzilong** [comment]
我在另一个仓库里面复现了，我先看看

**Comment by fengzilong** [comment]
复现的原因是因为 @megalo/template-compiler 没有升级到 ^0.6.0

**Comment by auven** [comment]
我用 `megalo-demo` 复现出来了，原来是我引用 `vant-weapp` ，错把 `Toast` 等组件放进了 `Vue` 的 `components` 里面。

``` vue
<template>
  <div class="app">
    <img class="pic" :src="img">
    <img class="pic" src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png">
    <img class="pic" src="../../static/megalobox.jpeg">
  </div>
</template>

<script>
import Toast from "vant-weapp/dist/toast/toast"
export default {
  components: {
    Toast
  },
  data() {
    return {
      img: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
    }
  },
  created() {
  },
  mounted() {
  },
  methods: {
  }
}
</script>

<style lang="less">
.pic {
  width: 750rpx;
}
</style>

```

![image](https://user-images.githubusercontent.com/23731087/49915745-1b55df80-fed2-11e8-82ea-dead21da9eb2.png)

这里是我自己的疏忽，同时建议修改 `@megalo/target/lib/platforms/shared/index.js` ，避免出现这种错误
``` js
...
// 182行
if (!NAME_MAP[ imp.name ]) {
  return true
}
...
```

![image](https://user-images.githubusercontent.com/23731087/49915865-e007e080-fed2-11e8-99e2-b7daa6333a5c.png)

**Comment by fengzilong** [comment]
@auven 你能把
`components`
`NAME_MAP[imp.name]` 为 `undefined` 时的 `imp.name`
这两个打印出来我看下么

**Comment by auven** [comment]
![image](https://user-images.githubusercontent.com/23731087/49916054-fe221080-fed3-11e8-8016-1877c27c2549.png)

**Comment by fengzilong** [comment]
https://github.com/kaola-fed/megalo-aot/issues/42
新建了一个issue，后续版本会给出更友好的提示

**Comment by auven** [comment]
@fengzilong  感谢~
