### ISSUE TITLE
@megalo/target@0.5.0 处理分包里的图片路径错误

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo-aot#43]
在最新的 [`megalo-demo`](https://github.com/kaola-fed/megalo-demo) 中，如下

![image](https://user-images.githubusercontent.com/23731087/49929801-4c4c0980-fefe-11e8-8909-44ecaf7c912f.png)

![image](https://user-images.githubusercontent.com/23731087/49929897-7d2c3e80-fefe-11e8-869a-df4556a54966.png)

**Comment by fengzilong** [comment]
@megalo/target@0.5.3
