### ISSUE TITLE
megalo-demo 生产化脚本下打包，分包js被打包进了主包里面

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo-aot#49]
https://github.com/kaola-fed/megalo-demo/issues/6#issuecomment-449638953

**Comment by fengzilong** [comment]
有些场景下，分包代码是会被打到主包里面的

**Comment by fengzilong** [comment]
https://github.com/kaola-fed/megalo-demo/blob/a53c972273f535c9e25f6c2fa3789e7aff82190e/build/createBaseConfig.js#L46
把这行删掉再打包

**Comment by fengzilong** [comment]
有问题的话再 reopen

**Comment by auven** [comment]
@fengzilong  删除那一行之后确实可以了，感谢~
