### ISSUE TITLE
微信小程序页面分包，引入components下的自定义组件不能slot

### ISSUE THREAD

**Issue by wiexin** [kaola-fed/megalo-aot#54]
"@megalo/entry": "^0.1.1",
    "@megalo/target": "^0.5.2",
    "@megalo/template-compiler": "^0.6",
     "megalo": "^0.6"
![image](https://user-images.githubusercontent.com/18095039/50381300-6cc65180-06be-11e9-8b37-011ac8ca35eb.png)

![image](https://user-images.githubusercontent.com/18095039/50381311-a5fec180-06be-11e9-815e-e9bbe7b11525.png)

**Comment by fengzilong** [comment]
https://github.com/kaola-fed/megalo-aot/issues/69
