### ISSUE TITLE
将<config></config>写到vue文件时，target自动生成的入口代码没有被babel编译

### ISSUE THREAD

**Issue by bigmeow** [kaola-fed/megalo-aot#58]
## 问题描述
当不写index.js时,megalo-target的vue-entry会自动生成并注入部分index.js的代码：
```js
import Component from ${ JSON.stringify( '-!' + remainingRequest ) };
import Vue from 'vue';
Component.mpType = "${ entryKey === 'app' ? 'app' : 'page' }";
const app = new Vue(Component);
app.$mount()
```
代码地址:https://github.com/kaola-fed/megalo-aot/blob/03ef02b9d16f29f8822551e2a2e52c0894c5512e/packages/target/lib/frameworks/vue/loader/vue-entry.js

以aot中的[demo](https://github.com/kaola-fed/megalo-aot/tree/master/examples/vue-mp)为例，当编译后，打开dist目录下，找到生成后的js页面文件`dist/package/static/js/package/pages/demo/index.js`,在文件中搜索'const',可以看到下面的代码：
```js
_Users_bigMeow_GitHub_megalo_megalo_aot_examples_vue_mp_node_modules_vue_loader_lib_index_js_vue_loader_options_Users_bigMeow_GitHub_megalo_megalo_aot_examples_vue_mp_src_package_pages_demo_index_vue__WEBPACK_IMPORTED_MODULE_0__["default"].mpType = "page";
const app = new vue__WEBPACK_IMPORTED_MODULE_1___default.a(_Users_bigMeow_GitHub_megalo_megalo_aot_examples_vue_mp_node_modules_vue_loader_lib_index_js_vue_loader_options_Users_bigMeow_GitHub_megalo_megalo_aot_examples_vue_mp_src_package_pages_demo_index_vue__WEBPACK_IMPORTED_MODULE_0__["default"]);
app.$mount();
```
这里有两个问题：
- 生成的变量名路径过长，是文件的绝对路径转化成的变量名（不处理，交由混淆压缩插件处理即可）
- 存在es6的const关键词，没有被babel编译

## 造成的影响
UglifyJsPlugin 压缩混淆时会报错
```js
Unexpected token: keyword (const) 
```

**Comment by bigmeow** [comment]
暂时先这么解决了
https://github.com/kaola-fed/megalo-aot/pull/62/files

**Comment by fengzilong** [comment]
@megalo/target@0.6.2
