### ISSUE TITLE
分包引用主包的组件 默认 slot 有问题

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo-aot#69]
![image](https://user-images.githubusercontent.com/25175055/50627195-585f4000-0f6d-11e9-9c53-788b1910a577.png)

![image](https://user-images.githubusercontent.com/25175055/50627209-6319d500-0f6d-11e9-9165-ccdc75c2c31e.png)

![image](https://user-images.githubusercontent.com/25175055/50627213-690fb600-0f6d-11e9-99ce-c629e7f791e5.png)

**Comment by fengzilong** [comment]
@megalo/target 0.6.0
@megalo/template-compiler@0.7.3
megalo@0.7.3

升级下版本应该可以解决了，有问题的话欢迎再反馈~
