### ISSUE TITLE
MegaloPlugin.js:239:43报Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by jiangslee** [kaola-fed/megalo-aot#95]
https://github.com/kaola-fed/megalo-aot/blob/ae1e655d41bbfc3542d14745ecd71c93fd20ee80/packages/target/lib/plugins/MegaloPlugin.js#L239

问题：MegaloPlugin.js:239:43报Cannot read property 'unshift' of undefined
![image](https://user-images.githubusercontent.com/27892476/59191884-5b60fb00-8bb3-11e9-9f46-257c021f6ac1.png)

解决方案：按群里大佬所说的注释掉或加个判断就可以跑起来了
![image](https://user-images.githubusercontent.com/27892476/59191898-63209f80-8bb3-11e9-8baa-268074258709.png)

![image](https://user-images.githubusercontent.com/27892476/59192000-a844d180-8bb3-11e9-8d40-5278e537d52b.png)

**Comment by fengzilong** [comment]
https://github.com/kaola-fed/megalo-aot/pull/94

@megalo/target@0.7.3 版本已经修复这个问题了，升级下试试
